import { JSX as _jsx } from 'react/jsx-runtime';
import './globals.css'
import { Inter } from 'next/font/google'
import ClientApp from './ClientApp';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
        <title>{metadata.title}</title>
        <meta name="Description" content={metadata.description}></meta>
      </head>
      <body className={inter.className}>
        <ClientApp />
      </body>
    </html>
  )
}
